# Basic
title: HenryDu
subtitle: 用无所谓的态度过着随遇而安的生活
# welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: Hallo,ich heiße 杜立成.爱苹果、爱游戏、向往天空、喜欢下雨、相机在手上、骑车可以跑很远.不想要阅人无数希望能行云万里.喜欢python,热爱爬虫,Web可以写一点,挑战让生活变得精彩。
creator: <a href="http://henrydublog">@HenryDu</a>

url: "http://henrydublog.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: Blog
    description: My blog

# Navigation buttons in the front page.
nav:
    - {title: 微博, description: My weibo, url: 'http://weibo.com/tiantianplayworld'}
    - {title: 简历, description: My resume, url: 'http://henrydublog.com'}
    - {title: 关于, description: My aboout, url: 'http://henrydublog.com'}

    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    # disqus: onevcat
    # duoshuo:

# Social
social:
    weibo: tiantianplayworld
    github: HenryDLC
    twitter: henryduLC
    gplus: 101638713009817352746
    mail: 707116148@qq.com

# Google Analytics
ga:
     id: UA-104897325-1
     host: henrydublog.com
